# Generated by Django 3.2.13 on 2022-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, default='accounts/background/dafault.png', null=True, upload_to='accounts/background/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='accounts/dafault.png', null=True, upload_to='accounts/'),
        ),
    ]
