# Generated by Django 3.2.13 on 2022-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('poster_path', models.URLField()),
            ],
        ),
    ]
